export const GET_MOVIES_CATEGORIES = "GET_MOVIES_CATEGORIES";
export const GET_TV_CATEGORIES = "GET_TV_CATEGORIES";
export const GET_MOVIE_FROM_CATEGORY = "GET_MOVIE_FROM_CATEGORY";
export const GET_TV_FROM_CATEGORY = "GET_TV_FROM_CATEGORY";
